### PR TITLE
Change display name and description in install.rdf

### PR DESCRIPTION
**Pull request by bwiernik**

### CODE REVIEW

**Comment by fbennett** [comment]
I'm being too fussy there, this is fine. Revision traffic on the plugin will be sparse, we don't have to worry so much about the revision history; I'll just remove the comment separately.

Thanks!

**Comment by fbennett** [comment]
Ah! Didn't spot your followup. Thanks twice.

**Comment by fbennett** [comment]
The release (v1.1.4) is up now. Is the plugin updating automatically for you? I haven't tested that end of things yet.

**Comment by bwiernik** [comment]
Automatic updating is not working from 1.1.3 to 1.1.4

**Comment by fbennett** [comment]
Thanks for checking. The URL for the update spec file was wrong. I've tested 1.1.5 > 1.1.6, it should be working now.

**Comment by bwiernik** [comment]
Yes, working for me, too. Thanks.

**Pull request merged**
